### PR TITLE
Srujan/UI UX fixes

### LINKED ISSUE #123: Styling Consistency
Issue with styling consistency:

Image

Image

Image

### PR DESCRIPTION
**Pull request by srujankarthik**
- fixed the inconsistency between navbars
- added in a horizontal row separator b/w the nav and the content
- input validation to a min of 100 words to restrict the user to not summarise

### CODE REVIEW

File: client/src/pages/Home.tsx [hunk 1]
```diff
@@ -202,9 +216,14 @@ function Home(this: any) {
...
           <button
+            id="summarise-button-id"
             onClick={getSummary}
-            style={{ backgroundColor: "#2e7faa" }}
+            style={{
+              backgroundColor: "#2e7faa",
+              cursor: isButtonDisabled ? "not-allowed" : "pointer",
+            }}
             className="mt-8 ml-52 py-2 px-4 text-white rounded"
+            disabled={isButtonDisabled}
```
Comment (gracebilliris) [inline client/src/pages/Home.tsx:235]: It's good that we have the _disabled_ button for the less than 100 words case. However, it would be good to give feedback to the User that they need _at least_ 100 words.

**Review by gracebilliris — CHANGES_REQUESTED** [review]

**Comment by gracebilliris** [comment]
@srujankarthik @JamesBug404 both of you have fixed the margin issue?... 
@srujankarthik's [PR](https://github.com/SIS-Team-24/2023-SIS-Team-24/pull/133)
@JamesBug404's [PR](https://github.com/SIS-Team-24/2023-SIS-Team-24/pull/131)

**Comment by srujankarthik** [comment]
I just had a look at Roy's PR it looks like he has added in margin for the Questions page, whilst I've removed it to ensure that the horizontal ruler below the navbar is present @gracebilliris @JamesBug404

**Comment by srujankarthik** [comment]
Now it's dependent on which design is preferable amongst us

**Comment by srujankarthik** [comment]
@gracebilliris I put the changes as a video on discord, lmk if that's fine 🙂

**Review by gracebilliris — APPROVED** [review]
Looking good!

**Review by henrygoodman — APPROVED** [review]
MGMT
