### PR TITLE
srujan/homepage-fixes

### LINKED ISSUE #128: Bug(s): `Home` Page 🐛
Tasks:
- [x] Only show _sentiment anlaysis of the text is: ...._ and _emotion analysis result: ..._ once the `Sentiment` _button_ is pressed.
- [x] The `Sentiment` _button_ can be pressed when the _Text to be Summarised_ is empty.
- [x] Reduce the _height_ of the _textboxes_.

### PR DESCRIPTION
**Pull request by srujankarthik**
* Completed - Only show sentiment anlaysis of the text and emotional…analysis only when the button is pressed

 * Completed - The Sentiment button can be pressed when the Text to be Summarised is empty.

 * Completed - Reduce the height of the textboxes to 508 px.

### CODE REVIEW

**Comment by srujankarthik** [comment]
Screenshot 2023-10-07 at 8 43 49 pm
Screenshot 2023-10-07 at 8 44 38 pm

**Comment by srujankarthik** [comment]
The height of the text boxes is something I'm unsure, will need to discuss with the team but, the rest of it is done

**Review by gracebilliris — APPROVED** [review]
Looks good!

File: client/src/pages/Home.tsx [hunk 1]
```diff
@@ -143,19 +146,32 @@ function Home(this: any) {
...
+      // When the input is empty
+      // set all the states if a user clicks on the sentiment button
+      // this should also hold true and follow thru too (the states which are set)
+      // when a user inputs something in the text box and clicks on it
+      setSentimentText("None");
+      setSentimentScore(0);
+      setEmotionLabel("Not set");
+      setSentimentPlaceholder("Sentiment analysis of the text is:");
+      setEmotionalPlaceholder("Emotional analysis result:");
+      setPercent("%");
```
Comment (stephenb-coding) [inline client/src/pages/Home.tsx]: A lot of states here, not sure about the others but if `percent` is just the `%` symbol then it doesn't need its own state lol.

**Review by stephenb-coding — CHANGES_REQUESTED** [review]
The first time you run the sentiment analysis it won't have some of the formatting we want like the percentage symbol etc. until you've tried running it with an empty input first

image

File: client/src/pages/Home.tsx [hunk 2]
```diff
@@ -341,10 +358,9 @@ function Home(this: any) {
               onClick={getSentiment}
               style={{
                 backgroundColor: "#2e7faa",
-                cursor: isButtonDisabled ? "not-allowed" : "pointer",
               }}
               className="mt-8 ml-52 py-2 px-4 text-white rounded"
-              disabled={isButtonDisabled}
+              // disabled={isButtonDisabled}
```
Comment (gracebilliris) [inline client/src/pages/Home.tsx]: The Cypress test is failing because this button is no longer disabled?

File: client/src/pages/Home.tsx (hunk 1 above)
Comment (srujankarthik) [reply client/src/pages/Home.tsx]: yeah I couldn't really think of anything else to get it to work, i'm sure there must be better ways to do it but yeah we can def look into refactoring it

File: client/src/pages/Home.tsx [hunk 3]
```diff
@@ -168,9 +184,10 @@ function Home(this: any) {
       <hr className="h-px mt-2 border-0 bg-gray-300"></hr>
       <div className="flex justify-between mt-10 mx-60">
         <p className="flex items-baseline justify-start space-x-4 text-xl">
-          Sentiment analysis of the text is:
+          {sentimentTextPlaceholder}
           <span style={setSentimentStyle()} id="sentiment-result">
-            {sentimentText} {`${Number(sentimentScore)}%`}
+            {sentimentText !== "" &&
+              `${sentimentText} ${sentimentScore}${percent}`}
```
Comment (gracebilliris) [inline client/src/pages/Home.tsx]: The `percent` isn't coming through on the UI. The Cypress test is also failing because it assumes that the value has a percentage symbol (%) sign next to it.

**Review by gracebilliris — CHANGES_REQUESTED** [review]

File: client/src/pages/Home.tsx (hunk 2 above)
Comment (srujankarthik) [reply client/src/pages/Home.tsx]: @gracebilliris this was one of the criteria 
 The Sentiment button can be pressed when the Text to be Summarised is empty.
 Removing that enables that to happen

Comment (gracebilliris) [reply client/src/pages/Home.tsx]: We discussed this on discord but for the record: it wasn’t a criteria - it was bug. Something that shouldn’t work but does!

**Review by gracebilliris — APPROVED** [review]
Looks good!

**Review by stephenb-coding — APPROVED** [review]
